spring.application.name=ikonex

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ikonex
spring.datasource.username=brian
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:123y198y1984e1nkjsnccklnwcwuifewiuvbdjskvnwoihvouw kwnw3920y583y78tf4905gv}
jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174, https://ikonex-assessment-frontend.onrender.com}

# Server Configuration
server.port=8087
server.servlet.context-path=/api


